version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: turtle
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6.2
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .  # Dockerfile 所在目录
      dockerfile: Dockerfile  # 显式指定文件名（可选）
    container_name: idiom_demo
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      DB_HOST: mysql  # 使用服务名（容器内DNS自动解析）
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./configs:/data/conf  # 挂载本地配置目录

volumes:
  mysql_data:
  redis_data: