// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"xiuyiPro/internal/biz"
	"xiuyiPro/internal/conf"
	"xiuyiPro/internal/data"
	"xiuyiPro/internal/server"
	"xiuyiPro/internal/service/greeter"
	"xiuyiPro/internal/service/idiom"
	"xiuyiPro/internal/service/turtle"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, application *conf.Application, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := greeter.NewGreeterService(greeterUsecase)
	idiomRepo := data.NewIdiomRepo(dataData, logger)
	idiomUsecase := biz.NewIdiomUsecase(idiomRepo, logger)
	idiomService := idiom.NewIdiomService(application, idiomUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, idiomService, logger)
	turtleRepo := data.NewTurtleRepo(dataData, logger)
	turtleUsecase := biz.NewTurtleUsecase(turtleRepo, logger)
	turtleService := turtle.NewTurtleService(application, turtleUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, turtleService, idiomService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
