// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"xiuyiPro/internal/biz"
	"xiuyiPro/internal/conf"
	"xiuyiPro/internal/data"
	"xiuyiPro/internal/server"
	"xiuyiPro/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	turtleRepo := data.NewTurtleRepo(dataData, logger)
	turtleUsecase := biz.NewTurtleUsecase(turtleRepo, logger)
	turtleService := service.NewTurtleService(turtleUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, turtleService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
