// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"xiuyiPro/internal/data/ent/migrate"

	"xiuyiPro/internal/data/ent/idiom"
	"xiuyiPro/internal/data/ent/turtle"
	"xiuyiPro/internal/data/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Idiom is the client for interacting with the Idiom builders.
	Idiom *IdiomClient
	// Turtle is the client for interacting with the Turtle builders.
	Turtle *TurtleClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Idiom = NewIdiomClient(c.config)
	c.Turtle = NewTurtleClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Idiom:  NewIdiomClient(cfg),
		Turtle: NewTurtleClient(cfg),
		User:   NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Idiom:  NewIdiomClient(cfg),
		Turtle: NewTurtleClient(cfg),
		User:   NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Idiom.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Idiom.Use(hooks...)
	c.Turtle.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Idiom.Intercept(interceptors...)
	c.Turtle.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *IdiomMutation:
		return c.Idiom.mutate(ctx, m)
	case *TurtleMutation:
		return c.Turtle.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// IdiomClient is a client for the Idiom schema.
type IdiomClient struct {
	config
}

// NewIdiomClient returns a client for the Idiom from the given config.
func NewIdiomClient(c config) *IdiomClient {
	return &IdiomClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `idiom.Hooks(f(g(h())))`.
func (c *IdiomClient) Use(hooks ...Hook) {
	c.hooks.Idiom = append(c.hooks.Idiom, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `idiom.Intercept(f(g(h())))`.
func (c *IdiomClient) Intercept(interceptors ...Interceptor) {
	c.inters.Idiom = append(c.inters.Idiom, interceptors...)
}

// Create returns a builder for creating a Idiom entity.
func (c *IdiomClient) Create() *IdiomCreate {
	mutation := newIdiomMutation(c.config, OpCreate)
	return &IdiomCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Idiom entities.
func (c *IdiomClient) CreateBulk(builders ...*IdiomCreate) *IdiomCreateBulk {
	return &IdiomCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IdiomClient) MapCreateBulk(slice any, setFunc func(*IdiomCreate, int)) *IdiomCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IdiomCreateBulk{err: fmt.Errorf("calling to IdiomClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IdiomCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IdiomCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Idiom.
func (c *IdiomClient) Update() *IdiomUpdate {
	mutation := newIdiomMutation(c.config, OpUpdate)
	return &IdiomUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IdiomClient) UpdateOne(i *Idiom) *IdiomUpdateOne {
	mutation := newIdiomMutation(c.config, OpUpdateOne, withIdiom(i))
	return &IdiomUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IdiomClient) UpdateOneID(id int64) *IdiomUpdateOne {
	mutation := newIdiomMutation(c.config, OpUpdateOne, withIdiomID(id))
	return &IdiomUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Idiom.
func (c *IdiomClient) Delete() *IdiomDelete {
	mutation := newIdiomMutation(c.config, OpDelete)
	return &IdiomDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IdiomClient) DeleteOne(i *Idiom) *IdiomDeleteOne {
	return c.DeleteOneID(i.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IdiomClient) DeleteOneID(id int64) *IdiomDeleteOne {
	builder := c.Delete().Where(idiom.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IdiomDeleteOne{builder}
}

// Query returns a query builder for Idiom.
func (c *IdiomClient) Query() *IdiomQuery {
	return &IdiomQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIdiom},
		inters: c.Interceptors(),
	}
}

// Get returns a Idiom entity by its id.
func (c *IdiomClient) Get(ctx context.Context, id int64) (*Idiom, error) {
	return c.Query().Where(idiom.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IdiomClient) GetX(ctx context.Context, id int64) *Idiom {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *IdiomClient) Hooks() []Hook {
	return c.hooks.Idiom
}

// Interceptors returns the client interceptors.
func (c *IdiomClient) Interceptors() []Interceptor {
	return c.inters.Idiom
}

func (c *IdiomClient) mutate(ctx context.Context, m *IdiomMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IdiomCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IdiomUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IdiomUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IdiomDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Idiom mutation op: %q", m.Op())
	}
}

// TurtleClient is a client for the Turtle schema.
type TurtleClient struct {
	config
}

// NewTurtleClient returns a client for the Turtle from the given config.
func NewTurtleClient(c config) *TurtleClient {
	return &TurtleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `turtle.Hooks(f(g(h())))`.
func (c *TurtleClient) Use(hooks ...Hook) {
	c.hooks.Turtle = append(c.hooks.Turtle, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `turtle.Intercept(f(g(h())))`.
func (c *TurtleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Turtle = append(c.inters.Turtle, interceptors...)
}

// Create returns a builder for creating a Turtle entity.
func (c *TurtleClient) Create() *TurtleCreate {
	mutation := newTurtleMutation(c.config, OpCreate)
	return &TurtleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Turtle entities.
func (c *TurtleClient) CreateBulk(builders ...*TurtleCreate) *TurtleCreateBulk {
	return &TurtleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TurtleClient) MapCreateBulk(slice any, setFunc func(*TurtleCreate, int)) *TurtleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TurtleCreateBulk{err: fmt.Errorf("calling to TurtleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TurtleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TurtleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Turtle.
func (c *TurtleClient) Update() *TurtleUpdate {
	mutation := newTurtleMutation(c.config, OpUpdate)
	return &TurtleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TurtleClient) UpdateOne(t *Turtle) *TurtleUpdateOne {
	mutation := newTurtleMutation(c.config, OpUpdateOne, withTurtle(t))
	return &TurtleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TurtleClient) UpdateOneID(id int64) *TurtleUpdateOne {
	mutation := newTurtleMutation(c.config, OpUpdateOne, withTurtleID(id))
	return &TurtleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Turtle.
func (c *TurtleClient) Delete() *TurtleDelete {
	mutation := newTurtleMutation(c.config, OpDelete)
	return &TurtleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TurtleClient) DeleteOne(t *Turtle) *TurtleDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TurtleClient) DeleteOneID(id int64) *TurtleDeleteOne {
	builder := c.Delete().Where(turtle.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TurtleDeleteOne{builder}
}

// Query returns a query builder for Turtle.
func (c *TurtleClient) Query() *TurtleQuery {
	return &TurtleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTurtle},
		inters: c.Interceptors(),
	}
}

// Get returns a Turtle entity by its id.
func (c *TurtleClient) Get(ctx context.Context, id int64) (*Turtle, error) {
	return c.Query().Where(turtle.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TurtleClient) GetX(ctx context.Context, id int64) *Turtle {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TurtleClient) Hooks() []Hook {
	return c.hooks.Turtle
}

// Interceptors returns the client interceptors.
func (c *TurtleClient) Interceptors() []Interceptor {
	return c.inters.Turtle
}

func (c *TurtleClient) mutate(ctx context.Context, m *TurtleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TurtleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TurtleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TurtleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TurtleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Turtle mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Idiom, Turtle, User []ent.Hook
	}
	inters struct {
		Idiom, Turtle, User []ent.Interceptor
	}
)
