// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"xiuyiPro/internal/data/ent/schema"
	"xiuyiPro/internal/data/ent/turtle"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	turtleFields := schema.Turtle{}.Fields()
	_ = turtleFields
	// turtleDescCtime is the schema descriptor for ctime field.
	turtleDescCtime := turtleFields[8].Descriptor()
	// turtle.DefaultCtime holds the default value on creation for the ctime field.
	turtle.DefaultCtime = turtleDescCtime.Default.(func() time.Time)
	// turtleDescMtime is the schema descriptor for mtime field.
	turtleDescMtime := turtleFields[9].Descriptor()
	// turtle.DefaultMtime holds the default value on creation for the mtime field.
	turtle.DefaultMtime = turtleDescMtime.Default.(func() time.Time)
}
