// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"xiuyiPro/internal/data/ent/predicate"
	"xiuyiPro/internal/data/ent/turtle"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TurtleDelete is the builder for deleting a Turtle entity.
type TurtleDelete struct {
	config
	hooks    []Hook
	mutation *TurtleMutation
}

// Where appends a list predicates to the TurtleDelete builder.
func (td *TurtleDelete) Where(ps ...predicate.Turtle) *TurtleDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TurtleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TurtleDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TurtleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(turtle.Table, sqlgraph.NewFieldSpec(turtle.FieldID, field.TypeInt64))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// TurtleDeleteOne is the builder for deleting a single Turtle entity.
type TurtleDeleteOne struct {
	td *TurtleDelete
}

// Where appends a list predicates to the TurtleDelete builder.
func (tdo *TurtleDeleteOne) Where(ps ...predicate.Turtle) *TurtleDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *TurtleDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{turtle.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TurtleDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
