// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Idiom is the predicate function for idiom builders.
type Idiom func(*sql.Selector)

// Turtle is the predicate function for turtle builders.
type Turtle func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
