// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IdiomsColumns holds the columns for the "idioms" table.
	IdiomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "iid", Type: field.TypeString},
		{Name: "answer", Type: field.TypeString},
		{Name: "image", Type: field.TypeString},
		{Name: "difficulty", Type: field.TypeInt32},
		{Name: "creator", Type: field.TypeString},
		{Name: "state", Type: field.TypeInt32},
		{Name: "ctime", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "mtime", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// IdiomsTable holds the schema information for the "idioms" table.
	IdiomsTable = &schema.Table{
		Name:       "idioms",
		Columns:    IdiomsColumns,
		PrimaryKey: []*schema.Column{IdiomsColumns[0]},
	}
	// TurtlesColumns holds the columns for the "turtles" table.
	TurtlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "qid", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "answer", Type: field.TypeString},
		{Name: "category", Type: field.TypeInt32},
		{Name: "creator", Type: field.TypeString},
		{Name: "difficulty", Type: field.TypeInt32},
		{Name: "state", Type: field.TypeInt32},
		{Name: "ctime", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "mtime", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// TurtlesTable holds the schema information for the "turtles" table.
	TurtlesTable = &schema.Table{
		Name:       "turtles",
		Columns:    TurtlesColumns,
		PrimaryKey: []*schema.Column{TurtlesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IdiomsTable,
		TurtlesTable,
		UsersTable,
	}
)

func init() {
}
